security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            logout:
                path: /logout
                target: /signin
            form_login:
                login_path: signin
                check_path: signin
                enable_csrf: true

    access_control:
        - { path: ^/(signin|signup), role: PUBLIC_ACCESS }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
